### PR TITLE
GCS Input readers and Output writers

### PR DESCRIPTION
**Pull request by rbruyere**
Added Google Cloud Storage Readers and Writers. They were written to
fill the gaps between by the Files API and GCS readers and writers.

Readers:
All input readers take the same input as GoogleCloudStorageInputReader
GoolgeCloudStorageLineInputReader
Reads files line by line.
Returns
A tuple containing an other tuple and the Line
(File name, start position), line
File name : Name of the file the data came from
start position : Files index position for the start of the data
line : The data read till a '\n' was reached

GoolgeCloudStorageZipInputReader
Reads zip files returning each sub files contents
Returns
A tuple containing an other tuple and the file contents
((Zip file name, text file), file data)
Zip file name : Name of the zip file being processed
text file : Current file being outputed
data : contents of the file

GoolgeCloudStorageZipInputReader
Reads zip files returning each sub files content line by line
Returns
A tuple containing an other tuple and the file contents
((Zip file name, text file, start position), line)
Zip file name : Name of the zip file being processed
text file : Current file being outputed
start position : Files index position for the start of the data
line : The data read till a '\n' was reached

Writers:
GoogleCloudStorageMergedOutputWriter
Overloads the GoogleCloudStorageConsistentOutputWriter
Merges all the outputs generated (one per shard) into one file
All other writers already do this

### CODE REVIEW

**Comment by caioiglesias** [comment]
Awesome work!

**Comment by soundofjw** [comment]
We were able to swap our very outdated MapReduce library with an updated version that includes these changes.

We haven't done this yet on production, but all of our test cases are passing presently with these changes.

In fact, without this PR, we were seeing the GCS Output Writers sometimes not working at all. Once we migrated to `GCSMergedOutputWriter`, all was well.

**Comment by caioiglesias** [comment]
Why did you close it?

**Comment by soundofjw** [comment]
This is a great question! @rbruyere I'm using this successfully in production with only a few minor hiccups. I've got it pulled into https://github.com/soundofjw/appengine-mapreduce and we use it today @loudr.

Noticeable hiccups with `GCSMergedOutputWriter`:
* Sometimes blank lines are emitted into the resulting file.
* ... after thinking this was the only big thing we found. :+1:

**Pull request closed without merging**
